export const fieldMap = {
  firstName: "hiTj",
  lastName: "cdfp",
  email: "rfop",
  phoneNumber: "j74y",
  address: "uyNP",
  primaryLanguage: "59cz",
  birthdate: "1auD",
  genderIdentity: "eGd2",
  maritalStatus: "v9uP",
  race: "gdqF",
  highestEducationCompleted: "7pZQ",
  militaryStatus: "k2u4",
  ethnicity: "59En",
  isDisabled: "uGFw",
  healthInsuraceCoverage: "i2eS",
  housingStatus: "pqa9",
  householdSize: "k4aa",
  familyType: "od7a",
  monthlyHouseholdIncome: "vTPE",
  date: "h1ky"
};

export const otherMembersFieldMap = {
  2: {
    firstName: "67w7",
    lastName: "x1Q9",
    relationship: "eYNW",
    birthdate: "aqAW",
    genderIdentity: "iwtx",
    race: "cQRG",
    ethnicity: "o8MA",
    maritalStatus: "7J6d",
    highestEducationCompleted: "fodd",
    militaryStatus: "n6zV",
    healthInsuranceCoverage:"9agC",
    isDisabled: "rdtv"
  },
  3: {
    firstName: "aQyV",
    lastName: "gdRy",
    relationship: "6pPy",
    birthdate: "cTpE",
    genderIdentity: "pfrY",
    race: "78Uy",
    ethnicity: "9Rs4",
    maritalStatus: "qDcs",
    highestEducationCompleted: "moLa",
    militaryStatus: "9sfz",
    healthInsuranceCoverage: "oyBh",
    isDisabled: "6qXN"
  },
  4: {
    firstName: "bnuS",
    lastName: "eKHj",
    relationship: "sspw",
    birthdate: "vzDp",
    genderIdentity: "1RRb",
    race: "pmVD",
    ethnicity: "cSWq",
    maritalStatus: "oHNB",
    highestEducationCompleted: "kspP",
    militaryStatus: "gGDd",
    healthInsuranceCoverage: "b84e",
    isDisabled: "o9TG"
  },
  5: {
    firstName: "kpRp",
    lastName: "5YDA",
    relationship: "aqfv",
    birthdate: "mwvh",
    genderIdentity: "w41A",
    race: "bEC6",
    ethnicity: "9Lwr",
    maritalStatus: "f8WN",
    highestEducationCompleted: "3RVA",
    militaryStatus: "uzie",
    healthInsuranceCoverage: "nLmF",
    isDisabled: "8C7Y"
  },
  6: {
    firstName: "jeeb",
    lastName: "9rRu",
    relationship: "ttH9",
    birthdate: "8NMT",
    genderIdentity: "ob1M",
    race: "uufQ",
    ethnicity: "1VMM",
    maritalStatus: "sjkc",
    highestEducationCompleted: "inDB",
    militaryStatus: "eYSL",
    healthInsuranceCoverage: "sCEY",
    isDisabled: "86rK"
  }
}